"""empty message

Revision ID: c874b9835790
Revises: 60ef9e526b0d
Create Date: 2021-07-02 15:45:07.441260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c874b9835790'
down_revision = '60ef9e526b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1020), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicaciones_timestamp'), 'publicaciones', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publicaciones_timestamp'), table_name='publicaciones')
    op.drop_table('publicaciones')
    # ### end Alembic commands ###
